// Generated by scripts/build_anne_ai_archive.py. Historical engine settings.
#include <sourcemod>
#pragma semicolon 1
#pragma newdecls required

public Plugin myinfo = {
    name = "Anne compat AI engine settings", author = "Anne", version = "1.0",
    description = "Apply historical engine values after Confogl and restore on unload"
};

static const char g_Settings[][][64] = {
    {"boomer_exposed_time_tolerance", ""},
    {"boomer_vomit_delay", ""},
    {"hunter_committed_attack_range", ""},
    {"hunter_leap_away_give_up_range", ""},
    {"hunter_pounce_max_loft_angle", ""},
    {"hunter_pounce_ready_range", ""},
    {"tank_throw_min_interval", ""},
    {"z_pounce_crouch_delay", ""},
    {"z_pounce_silence_range", ""},
    {"z_tank_throw_force", ""},
    {"z_tank_throw_interval", ""}
};
ConVar g_Handles[sizeof(g_Settings)];
char g_Previous[sizeof(g_Settings)][128];

public void OnPluginStart()
{
    // This plugin loads BEFORE the AI and unloads AFTER it.
    for (int i = 0; i < sizeof(g_Settings); i++)
    {
        g_Handles[i] = FindConVar(g_Settings[i][0]);
        if (g_Handles[i] != null)
            g_Handles[i].GetString(g_Previous[i], sizeof(g_Previous[]));
    }
    ApplySettings();
}

public void OnConfigsExecuted()
{
    // Confogl replays the current mode's values in this forward as well.
    RequestFrame(ApplyAfterConfigs);
}

public void ApplyAfterConfigs(any data)
{
    ApplySettings();
}

void ApplySettings()
{
    for (int i = 0; i < sizeof(g_Settings); i++)
        if (g_Handles[i] != null && g_Settings[i][1][0] != '\0')
            g_Handles[i].SetString(g_Settings[i][1]);
}

public void OnPluginEnd()
{
    for (int i = 0; i < sizeof(g_Settings); i++)
        if (g_Handles[i] != null)
            g_Handles[i].SetString(g_Previous[i]);
}
