// Generated by scripts/build_anne_ai_archive.py. Historical engine settings.
#include <sourcemod>
#pragma semicolon 1
#pragma newdecls required

public Plugin myinfo = {
    name = "Anne 22-07 AI engine settings", author = "Anne", version = "1.0",
    description = "Apply historical engine values after Confogl and restore on unload"
};

static const char g_Settings[][][64] = {
    {"boomer_exposed_time_tolerance", "0.0"},
    {"boomer_vomit_delay", "0.0"},
    {"hunter_committed_attack_range", ""},
    {"hunter_leap_away_give_up_range", ""},
    {"hunter_pounce_air_speed", "700"},
    {"hunter_pounce_loft_rate", "0.055"},
    {"hunter_pounce_max_loft_angle", ""},
    {"hunter_pounce_ready_range", ""},
    {"jockey_pounce_air_speed", "700"},
    {"smoker_tongue_delay", "0.0"},
    {"tank_attack_range", "75"},
    {"tank_swing_interval", "1.2"},
    {"tank_swing_miss_interval", "0.0"},
    {"tank_swing_range", "75"},
    {"tank_throw_min_interval", "8"},
    {"tongue_dropping_to_ground_time", "0.5"},
    {"tongue_hit_delay", "13"},
    {"tongue_los_forgiveness_time", "1.5"},
    {"tongue_miss_delay", "3"},
    {"z_acquire_far_time", "5.0"},
    {"z_acquire_near_time", "0.5"},
    {"z_attack_flow_range", "50000"},
    {"z_charge_warmup", "0"},
    {"z_hunter_lunge_distance", "5000"},
    {"z_jockey_control_variance", "0.0"},
    {"z_jockey_leap_time", "0"},
    {"z_jockey_speed", "275"},
    {"z_pounce_crouch_delay", ""},
    {"z_pounce_silence_range", ""},
    {"z_spit_interval", "15"},
    {"z_spit_latency", "0.3"},
    {"z_spitter_max_wait_time", "0"},
    {"z_tank_attack_interval", "0.0"},
    {"z_tank_speed_vs", "225"},
    {"z_tank_throw_force", ""},
    {"z_tank_throw_interval", "8"},
    {"z_tank_walk_speed", "225"},
    {"z_vomit_interval", "15"}
};
ConVar g_Handles[sizeof(g_Settings)];
char g_Previous[sizeof(g_Settings)][128];

public void OnPluginStart()
{
    // This plugin loads BEFORE the AI and unloads AFTER it.
    for (int i = 0; i < sizeof(g_Settings); i++)
    {
        g_Handles[i] = FindConVar(g_Settings[i][0]);
        if (g_Handles[i] != null)
            g_Handles[i].GetString(g_Previous[i], sizeof(g_Previous[]));
    }
    ApplySettings();
}

public void OnConfigsExecuted()
{
    // Confogl replays the current mode's values in this forward as well.
    RequestFrame(ApplyAfterConfigs);
}

public void ApplyAfterConfigs(any data)
{
    ApplySettings();
}

void ApplySettings()
{
    for (int i = 0; i < sizeof(g_Settings); i++)
        if (g_Handles[i] != null && g_Settings[i][1][0] != '\0')
            g_Handles[i].SetString(g_Settings[i][1]);
}

public void OnPluginEnd()
{
    for (int i = 0; i < sizeof(g_Settings); i++)
        if (g_Handles[i] != null)
            g_Handles[i].SetString(g_Previous[i]);
}
